use_frameworks!
platform :ios, '10.0'

target 'DemoApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'TUIBarrage', :path => '../'
  pod 'TUICore', :path => "../../TUICore"
  pod 'SnapKit'
  pod 'Kingfisher'
  pod 'Toast-Swift'
end


post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['ENABLE_BITCODE'] = 'NO'
      end
    end
end
