# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

# 注：如果没有下载SDK，请直接执行后面代码：  sh init.sh

def pod_player(type) 
  pod "TXLiteAVSDK_#{type}",:path => "../../SDK/"
  pod 'TUIPlayer', :path => "../", :subspecs => ["#{type}"]
end

target 'TUIPlayerApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'TXAppBasic', :path => "./TXAppBasic/"
  pod 'TUICore', :path => "../../TUICore/"
  pod 'Toast-Swift'
  pod 'Alamofire'
  pod 'Kingfisher'
  pod 'SnapKit'
  pod_player('Professional')
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end