source 'https://github.com/CocoaPods/Specs.git'
platform :ios, "8.0"

target 'XiaoZhiBoApp' do

pod 'AFNetworking', '~> 3.1.0'
pod 'SDWebImage', '~> 3.8.1'
pod 'MJRefresh', '~> 3.1.1'
pod 'MJExtension', '~> 3.0.10'
pod 'Masonry', '~> 1.0.1'
pod 'MBProgressHUD', '~> 0.9.2'
pod 'BlocksKit', '~> 2.2.5'
pod 'ZipArchive'
pod 'QBImagePickerController'
#pod 'pitu', :path => './pitu/'
pod 'CWStatusBarNotification', '~> 2.3.5'

end
